### ISSUE TITLE
Multiple graphs for varying units

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#10]
Graphs should display values of matching units. There should be a separate graph for each unit type.

**Comment by jamstooks** [comment]
Done, but we may get some feedback on this from the beta...

**Comment by jamstooks** [comment]
Reopening this because I'm sure we'll get more feedback here. Here are a few thoughts for improvements.

- [ ] use tabs to show separate graphs for each unit, to use less real estate
- [ ] use a carousel-like option, with arrow buttons to the left and right for more graphs
- [ ] keep them as they are
- [ ] ?

 I'd love to hear some feedback from the Design Team on this.

**Comment by dodget** [comment]
Closing - No feedback provided.
