### ISSUE TITLE
NA and NP Marking

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#100]
The results are showing credits marked “Not Applicable” as “Not Pursued”, which isn’t correct. Not Applicable means the credit doesn’t apply to the institution while Not Pursuing means it does apply but the institution just chose not to report on it. The two have very different scoring implications.

**Comment by rerb** [comment]
Moved to separate issue #130: Subcategory scores should display as Not Applicable when an institution marks all the credits in the subcategory as Not Applicable.

**Comment by rerb** [comment]
Moved to separate issue #131: Column sorting doesn’t seem to work properly in cases not applicable / not pursuing. For example, if I create a sample of all associate's colleges and the scores on the three research credits, sorting doesn’t seem to change the relation of the scored campuses to not pursuing campuses, it just moves around some not pursuing campuses.

**Comment by rerb** [comment]
Fixed in stars commit aac02a16.
