### ISSUE TITLE
Reporter Scores need to be hidden

### ISSUE THREAD

**Issue by monika-aashe** [AASHE/bt#106]
Indicate "Reporter" for any scoring fields.

**Comment by rerb** [comment]
Are "hiding reporter scores" and "indicate reporter for any scoring fields" two separate things?  Seems like we're asking that the scores be both hidden and labeled?

**Comment by peltonc** [comment]
Scores in unscored reports (Reporter submissions) should not be available for benchmarking. I'm not sure the best way to do that. I think Monika is suggesting replacing the score in these cases with the text "Reporter".

**Comment by dodget** [comment]
@peltonc - So should we only be making Field data points available for Reporter submissions?

**Comment by peltonc** [comment]
Yep, that seems like the most elegant solution. 

I'm not sure if we need to indicate for the user what's happening when they select a score data point for a Reporter submission.

**Comment by peltonc** [comment]
@dodget - This one is critical for launch. We can't expose scores for Reporters.

**Comment by dodget** [comment]
@peltonc - I'm close to tying this one off, but I have one question.
Should Credit scores be hidden for reporters? I assume yes, but I'm not sure why I am second guessing myself.

**Comment by monika-aashe** [comment]
It looks like @peltonc is out of the office today but I'm quite sure that scores should be hidden for credits, as well as overall and anything else (I don't know if we're planning to show subcategory or category scores but if so, hide there too).

**Comment by rerb** [comment]
Yesterday Chris said yes, credit scores for reporters should be hidden, as subcategory and category scores. 

- Bob

> On Dec 7, 2018, at 9:01 AM, Tylor Dodge <notifications@github.com> wrote:
> 
> @peltonc - I'm close to tying this one off, but I have one question.
> Should Credit scores be hidden for reporters? I assume yes, but I'm not sure why I am second guessing myself.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 










Share ideas, ask questions, and network with your peers in AASHE 
Connect <http://community.aashe.org>, your new online community!

Connect 
with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

**Comment by dodget** [comment]
Great, thanks Monika and Bob.

**Comment by rerb** [comment]
Tylor fixed.
