### ISSUE TITLE
Name filter + Enter clears all selections

### ISSUE THREAD

**Issue by peltonc** [AASHE/bt#107]
I was typing the name of an institution and clicked Enter on my keyboard. This clears out everything that had been selected (both institution and data filters) and closes the popup, which means I had to start over. It's like a reset button. +1 (JDS can duplicate this bug).

**Comment by rerb** [comment]
You really want to hold up releasing the tool -- which is what production version ready means, right? -- for this?

**Comment by dodget** [comment]
Fixed locally. Will be included in the next deploy to dev.

**Comment by dodget** [comment]
Fix deployed to dev.
