### ISSUE TITLE
Advanced Data Filtering

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#11]
The prototype shows very basic data filters. We want advanced filters, that can drill down to the documentation field level.

**Comment by monika-aashe** [comment]
Would be great to discuss filters on a future call. For example, what's the feasibility of developing filters based on AMS data (IPEDS, enrollment numbers, address and lat/long), versus data from the STARS report itself? What will be the defaults? Are we doing basic filters along with advanced?

**Comment by jamstooks** [comment]
I've moved this to the production milestone. Most of the work has been done on these filters, so we should be able to add them fairly quickly once we settle on them.

**Comment by jamstooks** [comment]
Done for now. Improvements tracked in other issues, like #59 .
