### ISSUE TITLE
Saved groups not displaying in Selection tab on dev site

### ISSUE THREAD

**Issue by peltonc** [AASHE/bt#126]
![screen shot 2018-09-06 at 13 56 15](https://user-images.githubusercontent.com/7784653/45176010-c15fc280-b1dc-11e8-87a3-202036ecd548.png)

**Comment by dodget** [comment]
Thanks, Chris!

Fixed locally. Will be pushed to staging on next deploy.

**Comment by dodget** [comment]
Fixed and deployed to stars-bt-dev. Closing.
