### ISSUE TITLE
Column sorting doesn’t work in cases of not applicable / not pursuing.

### ISSUE THREAD

**Issue by rerb** [AASHE/bt#131]
Column sorting doesn’t seem to work properly in cases not applicable / not pursuing. For example, if I create a sample of all associate's colleges and the scores on the three research credits, sorting doesn’t seem to change the relation of the scored campuses to not pursuing campuses, it just moves around some not pursuing campuses.

**Comment by dodget** [comment]
Resolved! Closing.
