### ISSUE TITLE
Make it easier to compare an institution against the overall average

### ISSUE THREAD

**Issue by peltonc** [AASHE/bt#132]
I'm not sure the best way to accomplish this, but it seems like a common question will be "How does my institution's performance compare against the overall average?" At the moment, there's no easy way to do that.

One potential solution would be to add "Select All" to the Ratings filter. That would at least allow a user to include all institutions and select them as a group.

**Comment by juliandsmith** [comment]
A Select All button is now available in association with the Ratings filter so I think this ticket has been accomplished. Closing for now but please reopen if I'm missing somthing.
