### ISSUE TITLE
Display a standard navigation menu on every view

### ISSUE THREAD

**Issue by peltonc** [AASHE/bt#134]
We have talked about this before, but the addition of the Dashboard makes me wonder again if it is too much to ask users to navigate to three different corners of the screen? Instead, should there simply be a series of circular icons that always appear in the upper right corner?:

Home or List icon (Dashboard)
Institution icon (Select institutions/reports)
Data/filter icon (Select data points)
Info icon (About)

**Comment by rerb** [comment]
Disagree that it's "too much to ask users to navigate to three different corners of the screen".
