### ISSUE TITLE
Vertical scroll bars missing

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/bt#141]
I'm not sure if it is intentional but that the vertical scroll bar is missing on the  BT landing page.  The up and down arrows and page down or up keys also don't work unless I first click the header. On my screen size and resolution, I can't see the featured benchmarks without scrolling down so this feels like a pretty significant problem. 

I should also mention that clicking anywhere else on the star map background makes the up or down bottons stop working, which means if I scroll down and then click the star map, it's impossible for me to scroll back up (since the header isn't visible anymore). I actually have to reload to get back to the top.

There is also no vertical scroll bars on the visualizations, which is kind of annoying. The up and down buttons work on these pages at least but it would be nice to have a scroll bar if possible.

**Comment by dodget** [comment]
Nice catch @juliandsmith .

It appears that the issue comes from the way that the background image is constructed, with the need to layer the starscape over the linear gradient of STARS blues. Locally, I layered them in a different way, which allows key scrolling from any position, and confirms that this is the problem.

The best solution is to create a single png of the background, so we no longer need to layer images.

**Comment by juliandsmith** [comment]
Cool! I just noticed that the same scrolling challenges also happen in the institution and data point selection menus. Down arrows / page down don't seem to work, regardless of what I cl for me. It's especially a challenge with the institution selection menu - it means I can only see the first 4 institutions in the results of any search/filter. 

I did discover that I can select the intro text and just keep selecting the text in order to get the menu to scroll down but that's pretty cumbersome.

**Comment by rerb** [comment]
Fixed.  Scroll bars are not visible, but scrolling by mouse and keyboard works again.

**Comment by juliandsmith** [comment]
The scroll bars are still really wonky for me. In Chrome, I now see 2 vertical scroll bars right next to each other:

![image](https://user-images.githubusercontent.com/15839046/50656649-eaf9e200-0f61-11e9-8c26-c0abfff8422c.png)

The rightmost one looks active (i.e., has a darker bar that I can move up or down) but it doesn't actually seem to do anything. The left one has no darker bar to move up or down but clicking on the up or down arrows at the top and bottom of it does actually scroll up or down. 

It could be a source of user frustration/confusion.

**Comment by dodget** [comment]
Thanks for reopening this. I believe it's now resolved in production.

**Comment by dodget** [comment]
Resolved.
