### ISSUE TITLE
Add Export Functionality

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#16]
- [x] Excel
- [ ] PDF

**Comment by jamstooks** [comment]
Assigning to @rerb  for the Excel/CSV export.

**Comment by jamstooks** [comment]
I wonder if we can use CSS to get the browsers "print to PDF" function to work for this?

**Comment by rerb** [comment]
CSV export released.  Punting on PDF export (for now, or forever); users can use their browser's Export as PDF or Print ... to PDF options in the meantime to get PDF export.
