### ISSUE TITLE
Test Firefox/Mac

### ISSUE THREAD

**Issue by rerb** [AASHE/bt#169]

**Comment by dodget** [comment]
Looks good!

Login page: working

Landing page:
-- shows
-- shows user benchmarks
-- shows featured benchmarks
-- New Benchmark works
-- Saved benchmark can be loaded
-- Logout works

Tool page:
-- shows
-- entity selection works
-- datapoint selection works
-- data can be exported
-- benchmark can be saved
-- Public benchmark can be loaded

About page:
-- shows
-- tabs work
