### ISSUE TITLE
Enhance mobile support

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#18]
Fully test on mobile.

**Comment by jamstooks** [comment]
- [ ] Graphs should use click, instead of mouse-over for pop-up box details.

**Comment by peltonc** [comment]
Crystal raises a good point about the orientation of the search filter and data filter buttons. I wonder if locating them together would be more mobile-friendly.

**Comment by jamstooks** [comment]
I personally like the positions, as they tie in to the axes of the graph, but we can definitely discuss this.

**Comment by jamstooks** [comment]
Look into reported scrolling issues.

**Comment by juliandsmith** [comment]
All I see when I open the URL in Chrome on my Android is the faded STARS swoosh. I don't see any text or menu buttons, even if I try to scroll around.

**Comment by dodget** [comment]
Login and about page have been optimized for mobile. Moving to landing page.

**Comment by dodget** [comment]
Closing this issue. After recent work, mobile is more clearly supported, and the issue is overly vague. Please, open a new issue with specific request if needed.
