### ISSUE TITLE
Metric vs Imperial visualization

### ISSUE THREAD

**Issue by dodget** [AASHE/bt#183]
The toggle between metric and imperial units is currently represented as an on-off switch labeled 'metric.' This gives an on-off feeling rather than a toggle, and although it is easy inferred what the user is doing, it isn't explicit.

I think it should be changed to a 'M | I' icon [toggle button](https://material-ui.com/lab/toggle-button/).

**Comment by peltonc** [comment]
I like that! Apparently, 'SI | IP' would be more correct technically.

**Comment by dodget** [comment]
Done, and published in latest release.
