### ISSUE TITLE
Chart bars and hover text are out of alignment

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/bt#196]
In charts with multiple data points, the hover text seems to present the data in reverse order from chart. For example, in this image the Academics bar is the last one for each institution but it appears first in the hover text:

![image](https://user-images.githubusercontent.com/15839046/50657781-74f77a00-0f65-11e9-9800-ef741e9d25fe.png)

This is potentially quite confusing for users. The order of the bars should be aligned with the order of the hover text.

**Comment by dodget** [comment]
Thanks Julian. This is resolved locally. I'll update this issue when it is resolved in production.

**Comment by dodget** [comment]
Deployed to production. Closing.
