### ISSUE TITLE
Changing the name of a saved group creates duplicate entry

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/bt#197]
There seems to be a bug related to changing the name of a saved group generating a legacy group that can't be edited. 

I created one saved group of all US participants and another group of all Canadian participants. After adding the US in aggregate, I changed the name of the saved group. Now the chart shows two US groups, one with the old name and one with the new name:

![image](https://user-images.githubusercontent.com/15839046/50658762-6068b100-0f68-11e9-8d15-df9c83c10fe7.png)

When I try to edit the institution selection to fix this issue, I don't actually see the old group - just the new one:

![image](https://user-images.githubusercontent.com/15839046/50658829-9c037b00-0f68-11e9-9cba-93e6b2116672.png)

I can remove the group with the new name but the old entry just seems to persist. Even after I remove both other groups, the one with the old name still appears in the chart. Ultimately, I had to close out and come back to the tool to get it to go away.

**Comment by dodget** [comment]
This is interesting. Thanks for the detailed documentation. As of yet, I haven't been able to reproduce this. Should these be the steps to reproduce?

1. Create group of US institutions
2. Give group generic name.
2. Add US group as "Aggregate"
3. Change name
4. Now the group displays twice (once with old name, once with current name)

**Comment by dodget** [comment]
I've figured a way this could happen, and found a way to hedge it from happening. I'll update once the bug is resolved.

**Comment by dodget** [comment]
Fixed in production.
