### ISSUE TITLE
Sorting results doesn't work as expected

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/bt#199]
As you can see in the image (from a simple sorting of all baccalaureate institutions by overall score), there is a sudden break in the sort (between Lewis and Green Mountain):
![image](https://user-images.githubusercontent.com/15839046/50726509-3e903b00-10dc-11e9-8895-d15d41033acb.png)

It looks like the sorting is organized in two separate groups for some reason. Each group is sorted correctly internally, but the collective list is wrong and potentially misleading if people don't scroll down and see that there are two groups. In this case, for example, the two highest scoring institutions are actually in the second group so someone trying to use the tool to create a ranking would be seriously wrong. 

I'm unable to determine why these groups are being sorted separately. As there are both old and new reports in each group, it doesn't seem to be based on submission date or STARS version as I initially suspected. I thought perhaps it was just based on the number of entries being sorted but I don't encounter this problem when sorting Bronze, Silver, or Gold rated institutions by score.

I have confirmed the same problem when sorting research institutions by overall score and a similar but perhaps unrelated issue in sorting Associate institutions (two institutions just don't change at all when the results are sorted). Strangely, I don't encounter the problem when sorting Masters institutions by score.

**Comment by dodget** [comment]
Thanks Julian. From first glance it looks like the behavior revolves around `Reporter` values in the column that is being sorted. I would say that a solution would be to treat `Reporter`, `NA`, and `NP` values as zeros, but that would mean that they artificially appear favorably when sorting fields that 0 is an optimal value.

I'll try to find an optimal solution.

**Comment by juliandsmith** [comment]
Interesting.  I don't think there are many cases when 0 is optimal - I can't think of any off the top of my head - so that seems like it could work.

**Comment by dodget** [comment]
Ok, I'll try to make it work.

**Comment by juliandsmith** [comment]
I'm not sure if it is related, but Chris reminded me that the sort on the existing [participants and reports page](https://stars.aashe.org/institutions/participants-and-reports/
) of the website is also buggy. Specifically, sorting by Version, Rating or Submission Date seems to create a somewhat similar issue in which the first group is sorted correctly but the second group of institutions seems to ignore the sorting and is just listed alphabetically.

**Comment by dodget** [comment]
Resolved locally. I've set any non-numerical value to sort as `-1` so as to be distinguished from true `0` values. Will update this issue when it is deployed to production.

**Comment by dodget** [comment]
Resolved in production. Closing.
