### ISSUE TITLE
Some institutions don't seem to be associated with an institution type

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/bt#200]
This is a weird one. For some reason, The Ohio State University appears in the list of options when I search for Ohio or filter for Gold institutions but it doesn't appear in the list when I try to filter for doctoral/research institutions (which is what it should be and what it is in Membersuite). 

I checked their STARS reports and it turns out that the liaison had incorrectly labeled them as a Masters institution in both of their previous submissions. I thought that was the explanation, but it turns out that Ohio State also doesn't appear in the filtered lists of Masters institutions (or the list of baccalaureate or associates for that matter). 

I'm not sure which source the BT is supposed to pull institution type from (i.e., MS or the reports themselves), but Ohio State should be in one of these lists! My only guess is that somehow the tool recognized an inconsistency between the two sources and marked institution type as blank, which doesn't seem optimal. People are likely to rely pretty heavily on institution type filters to find peer institutions so we really need institutions to show up in the right place.

**Comment by dodget** [comment]
Interesting find. Thanks Julian.

**Comment by dodget** [comment]
It looks like the data is provided by the institution's "Institutional Boundary" on their latest submitted report. From research, I can make a guess that Institutional Boundary values changed slightly from creditset 2.0 to creditset 2.1.

Ohio State's institution type on their 2.0 report shows as `Master's` but the filter is looking for the value `Master`, which is the value for a 2.1 creditset. If these definitions shift in future creditsets, this is something to keep in mind.

I'll try to broaden the filter to account for these differences. Thanks again for this find.

**Comment by juliandsmith** [comment]
That makes sense. Nice investigative work!

**Comment by dodget** [comment]
Tried broadening the filter method on the API, but it proved cumbersome. So I fixed the issue in the "extract, transform, load" process in the Reporting Tool. It will require a STARS deploy, so I will update this issue once the fix is visible.

**Comment by peltonc** [comment]
Just capturing the fact that the institution types are listed in the STARS 2.2 Technical Manual are:

- Associate/Short-cycle [a new variant to be inclusive of countries where Associate's degrees don't exist]
- Baccalaureate
- Doctoral/Research
- Master’s
- Other (non-higher ed.) [a new type for participants such as high schools, adult education centers, and museums]

We can still change these in the Manual if we need to. FYI, the 2.1 Technical Manual used "Master's" as well, but the credit set in the Reporting Tool uses "Master" for some reason (most likely an error on my part).

**Comment by dodget** [comment]
Thanks Chris. It's really about what the value in the credit set is. As soon as those are known, I can easily map the values to something unified during the extract, transform, load (ETL) process with just few lines of code. 

The way this filter works in the BT is it takes the latest credit set (currently 2.1) and creates a select field with possible values (Associate, Baccalaureate, Doctoral/Research, Master). So, if those values change in 2.2, the filters will be changed automatically.

Rectifying the differences between credit sets is simple. For example, to rectify 2.0 values to 2.1 during the ETL, I change any value of `Doctorate` to `Doctoral/Research` and `Master's` to `Master`. This change is yet to be deployed. It's simple enough, but I just need to know about it.

**Comment by dodget** [comment]
Fix deployed. Looks good. Closing.
