### ISSUE TITLE
Field-level data from Not Applicable credits are incorrectly labeled

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/bt#201]
As you can see in the image, the tool sometimes displays "NP" (which presumaby stands for "Not Pursuing") when field-level data is requested for credits that have been marked as "Not Applicable".  This only seems to happen with 2.1 submissions; 2.0 submissions just show "--". 

![image](https://user-images.githubusercontent.com/15839046/50782229-74b4f280-1275-11e9-8b31-aff1f2ef11cd.png)

As there is a material difference in scoring and interpretation between Not Applicable and Not Pursuing, neither approach is correct. Instead, any field-level data requested from a Not Applicable credit should also be marked as "Not Applicable".  That way, readers will understand that data hasn't been provided because the credit isn't applicable to the institution.

**Comment by dodget** [comment]
Thanks for the detailed rundown.

**Comment by dodget** [comment]
Fixed in the "extract, transform, load" process. This is a process that is run in the Reporting Tool, and will require a deploy to that server. Will update this issue when fix is viewable.

**Comment by juliandsmith** [comment]
Good find! Yes, I think all fields associated with a credit that is not applicable should show not applicable, even for fields that didn't exist at the time. The applicability criteria don't often change much from version to version, but even if they did, it still seems more helpful (or at least less misleading) to mark new fields associated with these credits as not applicable.

**Comment by juliandsmith** [comment]
As the original issue here has been addressed, I'm going to resolve it and create a separate ticket for dealing with issues created by field changes among versions.
