### ISSUE TITLE
Null data is rendered incorrectly for 2.1 reports

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/bt#202]
It appears that a field with no information is rendered differently for 2.0 and 2.1 submissions. 2.0 submissions get a "--" while 2.1 submissions seem to get a "0". I confirmed by looking at the actual reports that no data was submitted in either case:

![image](https://user-images.githubusercontent.com/15839046/50787854-9918cb00-1285-11e9-8324-5ea9faf86a36.png)

A response of "0" incorrectly implies an affirmative response of zero rather than no information provided. For consistency and to avoid misleading users, "--" should be used instead of "0" in all cases when no information is provided.

**Comment by dodget** [comment]
@juliandsmith - Any chance you could save and share the benchmark pictured above publicly, and provide the link? It would help a lot for rooting this out.

**Comment by juliandsmith** [comment]
Sure, I believe this is the benchmark that the screenshot came from: https://benchmarks.aashe.org/YO0f7f

**Comment by dodget** [comment]
Thanks!

**Comment by dodget** [comment]
Found the issue in the `_pivotStarsData` function. Apparently in JS `(null * 100)` equals `0`. The bug is fixed locally. I'll update this issue when it is in production.

**Comment by dodget** [comment]
This is resolved in production -- meaning `0` is never shown for null. There is still the issue of some fields showing as `NP` vs '--'. But that has to be resolved by a deploy to the Reporting tool, and is being handled in another issue. Marking this as closed.
