### ISSUE TITLE
Label for data from not pursued credits isn't clear in 2.1 reports

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/bt#203]
As you can see in the image, data from fields in credits that weren't pursued is labeled differently for 2.0 and 2.1 reports:

![image](https://user-images.githubusercontent.com/15839046/50788898-a71c1b00-1288-11e9-8b1f-a70cc0bbd327.png)

In 2.0 submissions, fields from credits that weren't pursued are labeled with "--". In 2.1 submissions, these fields are labeled as "NP". For consistency and since some site users won't immediately understand what the NP abbreviation refers to, all data from Not Pursued credits should just be labeled in the same way as other blank data: "--".

**Comment by dodget** [comment]
Just to make sure I have this right:

Field data from Not Applicable credits: `Not Applicable`
Field data from Not Pursued credits: `--`

Or, field data from Not Pursued credits: `Not Pursued`

**Comment by dodget** [comment]
Fix deployed. Closing.
