### ISSUE TITLE
About/Help page edits

### ISSUE THREAD

**Issue by peltonc** [AASHE/bt#214]
Please edit the Overview page when you have the chance (new text in **bold**):

The STARS Benchmarking Tool allows AASHE members to compare colleges and universities based on the scores and metrics reported through the [Sustainability Tracking, Assessment & Rating System]**(http://stars.aashe.org)** (STARS). You can use the Benchmarking Tool to:

- Select institutions or create groups of institutions for comparison.
- Select data points and generate charts to compare your selected institutions or groups.
- Save your Benchmarks for later use or to share with others.
- Download data for further analysis.

**Please review the [Data Use Guidelines](http://stars.aashe.org/reports-data/data-use-guidelines/) before publishing STARS data.**

Notes

- Selecting an institution selects its most recent report, by default. 
- All scores display as percentages, i.e. the percentage of available points earned.
- When data points based on different units are selected (e.g., a percentage score and a weight or volume), separate charts will be generated. In other words, only like units are charted together.

**Contact

Have questions? Email [stars@aashe.org](mailto:stars@aashe.org).**

**Comment by dodget** [comment]
Changes made. Closing.
