### ISSUE TITLE
Replace featured benchmarks

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/bt#215]
Here are some new suggested featured benchmarks to replace the existing ones:

https://benchmarks.aashe.org/Fm9cf7
https://benchmarks.aashe.org/dO9eea
https://benchmarks.aashe.org/yia18a

**Comment by dodget** [comment]
@juliandsmith - Did something happen to these benchmarks? They aren't showing as Featured any longer. If you deleted them or made them non-public (assuming they were your saved benchmarks), we should probably choose new ones. If you didn't do that, then we should choose new ones and investigate how they were deleted.

**Comment by juliandsmith** [comment]
Doh! I cleared these out of my account. I didn't realize the featured ones were just linked to mine and they were cluttering up my saved benchmarks. Sorry!

Here are some new ones:

https://benchmarks.aashe.org/ZO09ba
https://benchmarks.aashe.org/Hs0bb4
https://benchmarks.aashe.org/pP1331

I won't delete them this time...

**Comment by dodget** [comment]
Not a worry! Part of the second run of development should include better site administration. Closing now.
