### ISSUE TITLE
Data showing from not pursued credit

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/bt#224]
This is a strange one. In [this benchmark](https://benchmarks.aashe.org/bWdef2), Washtenaw Community College appears as having 75% of their food and beverage expenditures on products that are third-party verified under one or more recognized food and beverage sustainability standards or Local & Community-Based. However, if you click the link, it takes you to [WCC's STARS report](https://reports.aashe.org/institutions/washtenaw-community-college-mi/report/2018-05-23/OP/food-dining/OP-7/), which indicates that this credit was "Not Pursued". 

I'm guessing what happened here is that WCC had entered data for this credit initially but switched to Not Pursuing during the review and revision process after reviewers indicated they hadn't done it correctly. In any case, as we decided in #203, if a credit is Not Pursued; all of the fields associated with that credit should be blank - "--".

**Comment by dodget** [comment]
Thanks Julian. This should be fixed in the next STARS deploy. I'll update this issue when it is in production.

**Comment by juliandsmith** [comment]
This appears to be fixed. Thanks!
