### ISSUE TITLE
Duplicate fields

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/bt#241]
I have a suspicion that this has something to do with STARS 2.2, but I noticed some duplicate field options when using the BT today (see the electricity and RECs fields): 
![image](https://user-images.githubusercontent.com/15839046/70677930-8f9a9e80-1c5e-11ea-936a-de12bffeeff4.png)

Obviously, this is likely to be confusing for users. Is there a way to consolidate these somehow?

**Comment by peltonc** [comment]
I think this is because we ask for electricity in kWh and convert to MMBtu (calculated field). I suppose we should add the unit to the field descriptors, right?

**Comment by peltonc** [comment]
@juliandsmith I made the change, so once it syncs over you will be able to see if that solution addresses the issue.

**Comment by juliandsmith** [comment]
Yep, this fixed it. Thanks!
