### ISSUE TITLE
Set up cron job to run STARS ETL and tell benchmarking tool it's ready

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#3]
We need a system for extracting, transforming, and loading STARS data into the tool.

- [x] Extract
- [x] Transform
- [ ] Transport
- [x] Load

**Comment by jamstooks** [comment]
- [x] Extract
- [x] Transform
- [ ] Load

**Comment by jamstooks** [comment]
Moving to Production for the "load" piece.

**Comment by jamstooks** [comment]
We discussed the load peace like this:

@jamstooks:

The current idea I'm working with is an endpoint on bt that accepts a pointer to the data, which bt can fetch with a worker.

So, every night at 3am or so, stars would run the ETL script to:
 1. generate the json files
 1. make them available at /static/etl/<randomhash>/
 1. issue a GET request to bt.aashe.org/api/new_data/?key=<randomhash>

When bt receives the GET request it would trigger a worker to:

 1. fetch the JSON files from stars.aashe.org/static/etl/<randomhash>/
 1. add temporary message to Benchmarking Tool that it is "fetching the latest data"
 1. flush out old data and run the loaddata script on the new JSON files
 1. remove temporary message
 1. log the event somewhere (and send an email?)

Note: this would need some error-checking, like ensuring that the data is indeed new and the JSON is valid and a roll-back option if necessary.

I'd appreciate your thoughts on this approach before I try to implement it (which won't be right away, so you have time). I guess some other approaches would be to try to set up another database and run the import on that then swap them out for less down time.

@rerb:

 > I like this idea, Ben.
 > How long is `loaddata` taking?

@jamstooks:

> `loaddata` is just taking a few seconds. !!

**Comment by jamstooks** [comment]
The loading management command is working now, and provides a quick way to load data into a local instance...

```
./manage.py load_etl initFixture
```

**Comment by jamstooks** [comment]
So I've done _almost_ all of this... there's just one bit left to do, and I was wondering if @rerb or @dodget would be interested in the last bit on the STARS end...? It should be really strait forward and easy. It just takes time that I'd rather spend on UX right now.

I've documented the entire process [here](https://github.com/AASHE/bt-backend/blob/master/docs/ETL.md).

The part that is outstanding is [Every night at ~3am the STARS app](https://github.com/AASHE/bt-backend/blob/master/docs/ETL.md#every-night-at-3am-the-stars-app). All the extract and transform code is already in the [bt_etl app](https://github.com/AASHE/stars/tree/benchmarking-utils/stars/apps/bt_etl) under the [benchmarking-utils](https://github.com/AASHE/stars/tree/benchmarking-utils/) branch of stars.

All that's left is to:
 1. write a management command (or maybe a celery task) that runs the etl script(s)
 2. archive (`tar.gz`) the fixture files
 3. move the archive it to `/var/www/stars/media/etl/[key].tar.gz`
 4. issues a get request to the bt api (`/api/etl/?key=[key]&time=[timestamp]`)
 5. write tests to make sure it's _super_ durable

> Note: I'd personally lean toward a management command, then you can run this manually whenever you need to and can schedule it with cron.

> Note: You might find the [load_etl](https://github.com/AASHE/bt-backend/blob/master/bt/apps/etl/management/commands/load_etl.py) management command (along with the [tests](https://github.com/AASHE/bt-backend/blob/master/bt/apps/etl/tests.py)) to be a good reference, although you might want to use `subprocess` instead of `os.system`.

If neither of you have time to work on this tomorrow or early next week, that's totally fine. I'll get to it eventually.

**Comment by rerb** [comment]
I’ll do.

In 
> write a management command (or maybe a celery task) that runs the etl script(s)
What are the etl scripts?  I should probably look around.

- Bob



> On Jul 26, 2018, at 6:14 PM, Benjamin W Stookey <notifications@github.com> wrote:
> 
> write a management command (or maybe a celery task) that runs the etl script(s)


-- 










Explore upcoming professional development opportunities 
<http://www.aashe.org/events-education/> including exciting workshops, free 
webinars and more!

Share ideas, ask questions, and network with your peers 
in AASHE Connect <http://community.aashe.org>, your new online community!


Register now <http://www.aashe.org/conference/> for the 2018 AASHE 
Conference & Expo happening October 2-5, 2018 in Pittsburgh, PA!




 
Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>






-- 










Share ideas, ask questions, and network with your peers in AASHE 
Connect <http://community.aashe.org>, your new online community!

Early 
bird registration now open for the 2018 AASHE Conference & Expo
happening 
October 2-5, 2018 in Pittsburgh, PA! Register today and save 
<http://www.aashe.org/conference/>!

 Connect with us:   Website 
<http://www.aashe.org/> | Facebook <https://www.facebook.com/aasheorg> | 
Twitter <https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

**Comment by rerb** [comment]
Done.
