### ISSUE TITLE
Branding - add header or footer

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#33]
- [x] add color theme
- [x] favicon
- [ ] header or footer
- [x] include watermark

**Comment by jamstooks** [comment]
Moving remainder to Production milestone.

**Comment by rerb** [comment]
Are we going to put a header and footer on the tool?  Will discuss at next STARS team meeting.

**Comment by rerb** [comment]
Consensus is to style App Bar to blend with STARS website style.  Footer like the Hub was requested, but has been rejected -- a footer appropriate for a web page (or at least the footer on the hub) is inappropriate for this app.

**Comment by rerb** [comment]
Blocked until receipt of CSS stylesheets for new STARS website from SAI.

**Comment by rerb** [comment]
Unblocked -- persistent AppBar with nav burger menu will suffice.

**Comment by juliandsmith** [comment]
Seems like this one is done as the burger menu has been added. Closing this one.
