### ISSUE TITLE
Provide a "select all" button in search results

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#35]
A select all would select all the search results.

**Comment by peltonc** [comment]
I think users will want to "select all" to create a group as well, for example, to display the average for all Gold institutions or all US institutions.

**Comment by dodget** [comment]
This feature has been added locally, and will be moved to dev site soon. It added a bit of unexpected complexity, as it requires the management of three potential "selection states":
- selected All
- selected Some
- selected None

Seems to be working great!

**Comment by dodget** [comment]
I've made some modifications to invoke bulk methods. It reduces the number of requests from n to 1 per each select all click. Works very well, and appears to be production ready.

**Comment by rerb** [comment]
Hey, Tylor.  Why reopen this?

**Comment by dodget** [comment]
I had prematurely closed it. I think it can be closed now.
