### ISSUE TITLE
DataView initial appearance

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#39]
Shortcuts to example data views.

**Comment by monika-aashe** [comment]
Add your suggestions, comments: https://docs.google.com/document/d/18HHAG-ZmaoEKS6BSNH7N_nflQqk4_aMy_sv1OZqG5Bk/edit

**Comment by juliandsmith** [comment]
Here are some ideas:

Energy Consumption per Square Foot at Doctoral/Research Institutions
Percentage of sustainability courses at Baccalaureate Colleges
Percentage not driving alone at Community Colleges
GHG Emissions per person at Masters Institutions

**Comment by jamstooks** [comment]
Tylor is starting to work on this. We had a discussion via email about this and I thought the content really belonged here, so I'm adding it for good measure. Looking forward to seeing his design...

@dodget 
> I just came up with a basic idea before I started doing anything in react. I'd like to run it by you both before I go any deeper.
>
>The idea is two rows, with horizontal scrolling (if scrolling is needed). The first row includes "New Graph" and the user's "bookmarked" graphs. The second row will contain the "tour" (if we can come up with one) and graphs created by AASHE staff.
>
>I think it's pretty simple. Netflix has gotten people comfortable with horizontal scrolling. Horizontal scrolling is typical phone behavior as well, so that makes scaling to phones all the easier.

@jamstooks
> Horizontal scrolling is cool with me. I think it'll be interesting to think about what "new graph" means? Does that just open the "select institutions" dialog? And when/why/how would we get back to this landing screen?

@dodget 
> "New Graph" would bring you to the blank page that we currently start with on the BT.

**Comment by dodget** [comment]
Just realized I did not provide a link.
https://jlw819yojv.codesandbox.io/

**Comment by jamstooks** [comment]
Very cool! What will the three buttons do?

**Comment by dodget** [comment]
First - Info. Provide full title and description of the bookmark, maybe date created. There is truncation on the card for titles and descriptions that are too long.
Second - Edit. If it is a user saved bookmark, then they can edit the title and description.
Third - Delete. If it is a user saved bookmark, then they can delete the bookmark.

**Comment by jamstooks** [comment]
How do you envision the tour working with this _landing page_? Would there be a button to "take the tour" or something that would take the user to a fresh benchmark?

**Comment by dodget** [comment]
Closing as the landing page has been added. Edits and editions to the landing page should be entered in their own issues.
