### ISSUE TITLE
Retain last state for users

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#43]
When a user comes back to site, it would make sense to provide a way for them to start back up where they left off... 

This is likely tied to #39. Maybe the first box... "continue where you left off" or something like that?

**Comment by jamstooks** [comment]
@dodget - I've assigned this to you for now, but I can handle the integration once you've designed the interface.

**Comment by dodget** [comment]
Feature deployed to stage. Passing all tests. Closing
