### ISSUE TITLE
Add support for changing CreditSets

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#45]
Currently we only support 2.1 submissions, but we will need to utilize the versioned-nature of CreditSets to support more submissions.

@question - Do we support pre 2.0 submissions?

**Comment by peltonc** [comment]
Curious how this will work. 

Will the tool only include the fields in the current version of STARS or will it also include fields that have been dropped over the years? The latter could be messy and confusing. 

When a new credit set is released, will the field names in the tool be updated (for this fields that are linked between versions)?

**Comment by jamstooks** [comment]
Good question. I guess I had pictured this always displaying the "latest" credit set's categories... credits where we select Data Points, but the data would show up for previous versions as necessary. This is how the Data Displays does it.

Does that sound like it works? Are we supporting 1.* credit sets too?

**Comment by peltonc** [comment]
I think that makes sense. 

We should discuss version 1. The subcategory structure is pretty different, so I'm not sure how those scores would work (if at all) alongside v2. Many of the numeric fields will still be valuable, however (energy use, waste, GHG emissions, and so on), so it seems like we would want to provide those to allow an institution to track its progress over time.

**Comment by peltonc** [comment]
I have some related questions about the long-term implications of adopting a specific organizational structure for the data point filters. I don't imagine the subcategories will go away, but I'm less sure about categories and credits. 

- What will happen when two credits are merged in v2.2 (as planned)? 

- What will happen if v3.0 ends up based solely on subcategory-level scores (no more categories or credits)?

**Comment by jamstooks** [comment]
I've set this up so that it will always use the latest version of STARS to generate the data points. Any selected report that has a previous version of that data point will display data. You can see this quickly by selecting one of the Colorado schools and then selecting multiple versions (in the "Selection" tab).

Currently this is only running for 2.* reports, but it can be extended to 1.* if you'd like to see how that works.

The only scenario where this might be an issue is with saved bookmarks, but even then, the user will still get data for any data point that wasn't removed in the latest version.

The ETL takes significantly longer (fyi @rerb and @dodget ) at almost an hour now with the additional data and version lookups, but the loading time is still under 3 minutes. The two management commands are `run_etl` (stars) and `load_etl` (bt-backend).

**Comment by jamstooks** [comment]
FYI this is up on stars-bt-stage
