### ISSUE TITLE
Integrate Authentication

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#46]
- [x] get `django-membersuite-auth` working with Django 2.0 and Python 3
- [ ] add authorization to api
- [ ] build the two django views and login screen

**Comment by jamstooks** [comment]
@rerb @dodget  - if either of you have time in the next two weeks to take a stab at the first item, that would be great. Otherwise, happy to deal with it when I get back...

**Comment by jamstooks** [comment]
Auth design plan:

**Comment by jamstooks** [comment]
# Auth Plan

**Member View** `/tool/`

Displays the whole tool with access to saved views from within the tool.

**Public View** `/Etk34e/` (example URL)

Just displays the DataView part of the tool using the saved filters.

### Note

Sharing a view with another member in a way that they can modify it themselves would require significant additional features in the Member Vew.

**Comment by jamstooks** [comment]
@rerb @dodget if either are you are interested in taking the authorization piece of this issue, let me know.

We'd basically just have to add member only [permissions](http://www.django-rest-framework.org/api-guide/permissions/) to each api endpoint. We'll create one more public endpoint that serves the public view data later that will be public.

**Comment by dodget** [comment]
@jamstooks I am currently flushing this out.

Question: How do we want the login form to appear?

I can create a login form at `templates/registration/login.html` and make it look as material as I can. Or, would you like me to serve up a material-ui form from the react app?

The former seems simplest.

**Comment by jamstooks** [comment]
That makes sense to me. How about these views?

- [ ] `views.LoginView`
- [ ] `views.MemberView`
- [ ] `views.PublicView`

If `LoginView` is just a standard Django login view using a basic HTML form, then all other calls to the API will include the correct session information and we won't have to do much auth in the react app itself...

**Comment by jamstooks** [comment]
`PublicView` would serve the tool but without the Institution or Data Point components, just the Data View. I'm going to have to update the react app to handle that...

**Comment by dodget** [comment]
Ok, the branch `authentication` on bt-backend has working authentication, and a material design form. Should I wait to issue a pull request until the beta is over?

**Comment by jamstooks** [comment]
I think a pull request is fine right now. If it doesn't conflict with the
main URL then we should be fine...

**Comment by dodget** [comment]
Finished!
