### ISSUE TITLE
Add landing page

### ISSUE THREAD

**Issue by dodget** [AASHE/bt#57]
Create a landing page for the application

**Comment by dodget** [comment]
@jamstooks - I've done a very basic integration between the landing page and the benchmarking tool in the 'landing-page' branch. There is a bit of cleanup there that I will get to this week. I am going to start on adding bookmarks to the backend tomorrow. I think we should call them 'benchmarks,' tough.

**Comment by jamstooks** [comment]
is this a dupe of #39

**Comment by dodget** [comment]
Yes, it is.

**Comment by jamstooks** [comment]
Closing in favor of #39;
