### ISSUE TITLE
Selecting field should add it to graph

### ISSUE THREAD

**Issue by dodget** [AASHE/bt#59]
When you get down to selecting a field, you shouldn't have to click "add value." Clicking the field should be enough to add the value. In my opinion, anyways.

**Comment by dodget** [comment]
To be clear, I only mean this at the "field" level.

**Comment by peltonc** [comment]
How would a user add multiple fields? Just select another one?

**Comment by jamstooks** [comment]
I'm going to explore a pull-down with checkbox option for this, similar to the _keyword search_.

Adding it to the beta milestone optimistically.

**Comment by jamstooks** [comment]
I've removed the "add score" button in favor of a checkbox. This separates the selection of data points from the drill-down navigation, but the checkbox feels more intuitive than a separate button.

The only UX piece that isn't totally clean is when the pull-down is closed and the user wants to check or uncheck the box, the menu will open when clicking the checkbox. Ideally, checking the checkbox shouldn't open or close the pull-down.

I've created another issue for this #88.

@dodget @peltonc - If this feels like a solution that works, please let me know and I'll close this ticket.
