### ISSUE TITLE
Need pattern for closing pop-ups.

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#61]
It’s not immediately clear that simply clicking X to close a pane saves search parameters. Maybe add a “Next” button if the other side hasn’t been completed or a “Show Chart” button if it has.

**Comment by jamstooks** [comment]
What do we think about "OK"? If we'd like something a bit _smarter_ that says "next", then we can decide on that ahead of production.

**Comment by dodget** [comment]
@rerb - I'd say what we have currently is good. Especially when the dialog isn't full screen. 

I'd be in favor of closing this issue.

**Comment by rerb** [comment]
Your wish ... ;-)
