### ISSUE TITLE
Add Overall Score

### ISSUE THREAD

**Issue by jamstooks** [AASHE/bt#75]
Can we add “All” to the list of categories to make overall scores available? Is there another way to go about it?

That's an interesting idea. I had thought it would be a separate button, but All (Overall Score) sounds intuitive.

**Comment by jamstooks** [comment]
The checkbox was easiest, so I've added that for the beta. Will push back to production for "All" option.

**Comment by jamstooks** [comment]
What about other data points we might want to show in the table, like:

- Rating
- Date Submitted

Should we have a pull-down above category that functions similarly, but has Overall Score, Rating, and Date Submitted as options?

**Comment by peltonc** [comment]
I'm not sure I understand how data points like that would display. I'm also not sure of the need since institutions/reports can be filtered and selected based on rating and version.

**Comment by jamstooks** [comment]
So reports can be filtered that way, but that data doesn't show up as a column that can be sorted...
