### ISSUE TITLE
Selection pane should display rating for each report

### ISSUE THREAD

**Issue by peltonc** [AASHE/bt#92]
The results include the rating, date, and version of each report, e.g. "Silver: Mar 2018 (2.1)". I think the Selection pane and the report selector need to do the same. That will allow users to distinguish rated reports from unscored reports.

**Comment by dodget** [comment]
@peltonc - Did you mean for it to say something like "latest (Silver: Mar 2018 (2.1))" on the initial selection of an entity. Or say "latest" on the initial selection, and say "Silver: Mar 2018 (2.1)" on the report selector, and when a specific report has been selected?

**Comment by dodget** [comment]
The latter is cleanest, I think.

**Comment by peltonc** [comment]
I agree.

**Comment by dodget** [comment]
Excellent, thanks. Done locally. Will be pushed up to dev on next deploy.

**Comment by dodget** [comment]
Deployed to dev. Working well. Closing, please reopen if there are any issues.
